'use strict';

export const WARPSHIPTORANDOMDESTINATION = 'WARPSHIPTORANDOMDESTINATION';
export const REFUELSHIP = 'REFUELSHIP';
export const DAMAGESHIP = 'DAMAGESHIP';
export const REPAIRSHIP = 'REPAIRSHIP';
export const DRAINSHIPFUEL = 'DRAINSHIPFUEL';
export const CLOSEEVENT = 'CLOSEEVENT';
export const SETEVENTSTATE = 'SETEVENTSTATE';
export const GAINCREDITS = 'GAINCREDITS';
export const LOSECREDITS = 'LOSECREDITS';
export const INCREASEREACTOR = 'INCREASEREACTOR';
export const LOADCARGO = 'LOADCARGO';
export const UNLOADCARGO = 'UNLOADCARGO';



