'use strict';

export const WARPSHIPTORANDOMDESTINATION = 'WARPSHIPTORANDOMDESTINATION';
export const REFUELSHIP = 'REFUELSHIP';
export const DRAINSHIPFUEL = 'DRAINSHIPFUEL';
export const CLOSEEVENT = 'CLOSEEVENT';
export const SETEVENTSTATE = 'SETEVENTSTATE';



